baseURL = "http://hugo-journal.s3-website.us-east-2.amazonaws.com/"
languageCode = "en-us"
title = "Sarvesh's Journal"
theme = "ezhil"


[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://hugo-journal/?region=us-east-2" #your bucket here